### ISSUE TITLE
Max team players by permission

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/addon-bskyblock#12]
Hi,
is it already possible to make nondefault team sizes by permissions?

**Comment by Kryniowesegryderiusz** [comment]
I tried this and its not working. Im using luckyperms if it changes something.

**Comment by Poslovitch** [comment]
It is not implemented yet. I'll add this as a feature request on BentoBox.

**Comment by Poslovitch** [comment]
Closing

**Comment by Poslovitch** [comment]
Just found out it was already opened in Bbox's repo : https://github.com/BentoBoxWorld/bentobox/issues/114
