### ISSUE TITLE
Coop breaking blocks problem

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/addon-bskyblock#14]
When someone is in coop on island, where in settings breaking blocks is locked for coops player can broke them and there displays "island protected" message. But despite this message he still can break them.

**Comment by tastybento** [comment]
If the player is seeing the "Island protected" message then the plugin is correctly trying to stop the action, but another plugin is ignoring the event cancel and allowing it. What other plugins are you running? One of them is likely causing this issue. I recommend you remove plugins one by one until this problem stops.

**Comment by Kryniowesegryderiusz** [comment]
Yes, it was another plugin. Thank you. Could you also look at [this](https://github.com/BentoBoxWorld/bentobox/issues/297) issue? Its really annoying and problematic, when players are not fully added to island :/

**Comment by Poslovitch** [comment]
@Kryniowesegryderiusz Please note that we're developping BentoBox as a hobby. We know which issues are to be prioritised - we talk to each other on Discord - but IRL has to come first. Moreover, we're currently very busy and your issue will be very hard to fix as I personally could not reproduce it.
