### ISSUE TITLE
diffrent references in config bsadmin and asadmin

### ISSUE THREAD

**Issue by SgtLegoTown** [BentoBoxWorld/addon-bskyblock#16]
Asadmin and bsadmin in config
on line21 it says bsadmin and line 22 bskyblock but then on line 168 there stand askyblock and 
on line 171 asadmin but commands dont work
i found a alias bsb and the autofillin showed me the  bsbadmin command 
i uses the 030-snapshot bsbadmin version didnt give any output /island about did
its maybe somthing small but i still tought i reported it

**Comment by robert-beckley** [comment]
This is on their to do list. 

https://github.com/BentoBoxWorld/bentobox/projects/4#card-12581004

**Comment by SgtLegoTown** [comment]
i will keep next time first a look at this list ty.
