### ISSUE TITLE
Island members sometimes considered as visitors

### ISSUE THREAD

**Issue by Frozen-Craft** [BentoBoxWorld/addon-bskyblock#21]
**Describe the bug**
Some player don't take damages and can't place welcome sign 

**To Reproduce**
i don't know, it appear randomly :/

**Expected behavior**
Fix it beaucause it's a big problem that players can't make welcome sign and don't take any damage

**Screenshots**
Welcome warp:
http://www.noelshack.com/2018-43-2-1540306814-isbug.png
Islands Damages:
https://youtu.be/_FwZsg20R-E

**Server Information (please complete the following information):**
 - Database being used: Flat
 - OS: Debian 9
 - Java Version: Java 8
-  Minecraft 1.13 CraftBukkit v_1_13_R2
 - Other plugins

LuckPerms, WorldEdit, SkyGUI, EggCatcher, MinewebBridge, AdvancedBan, ProtocolLib, WorldGuard, HideAndCustomPlugins, Cobblegen, VoidGenerator, BentoBox, VoxelSniper, AdvancedBanGUI, TAB, CS-CoreLib, Vault, Essentials, EpicRename, QuickShop, Multiverse-Core, Citizens, VanishNoPacket, MythicMobs, Slimefun, EssentialsChat, Shop, EssentialsSpawn, DungeonsXL, CrateReloaded

**Additional context**
world guard flags are invincible: deny and Fall-damage : allow

**Comment by tastybento** [comment]
Does your server ever shutdown suddenly, like a machine reset or the Minecraft server is restarted by CRON?

**Comment by Frozen-Craft** [comment]
yes, once or twice he was stopped suddenly. Have you a solution to fix it?

**Comment by Poslovitch** [comment]
I'll move this issue as this is mostly related to BentoBox's protection.

**Comment by Poslovitch** [comment]
This issue was moved to BentoBoxWorld/bentobox#318
