### ISSUE TITLE
Can't paste schem

### ISSUE THREAD

**Issue by phloo75** [BentoBoxWorld/addon-bskyblock#23]
Everytime i try to create an island i will get this message in console:
`ERROR [BentoBox] Tried to paste schem for BSkyBlock_world but it is not loaded!`

I tried to run the /is in the bskyblock_world world but same problem. 

I got the newest version of both the addon and bentobox
![image](https://user-images.githubusercontent.com/24303063/47811921-4253ba00-dd47-11e8-844e-7b7548786b11.png)

Plugins:
![image](https://user-images.githubusercontent.com/24303063/47811970-63b4a600-dd47-11e8-92af-c367183465e6.png)

Thats basicly all the infomation i got. It's a custom schem, but i can paste it with worldedit, so i can't see any problems with that.

**Comment by phloo75** [comment]
The bentobox version is 0.11.0-alpha1
![image](https://user-images.githubusercontent.com/24303063/47812384-927f4c00-dd48-11e8-918d-18b099d55c94.png)

**Comment by Poslovitch** [comment]
Schem =/= schematic. Schems are Bentobox's format

**Comment by phloo75** [comment]
Well I just replaced the default island.schem with my own. I can't do that? Or?
![image](https://user-images.githubusercontent.com/24303063/47813599-d7f14880-dd4b-11e8-8bb1-8854a57136c8.png)

**Comment by Poslovitch** [comment]
Yes, you can't - schematics are not schems. Schems is the format handled and used by BentoBox. You must edit the schems using the in game command `/bsbadmin schem`. This video will help you along this process: https://www.youtube.com/watch?v=hFkP7hit3i4.

**Comment by tastybento** [comment]
@phloo75 If there is a problem loading the schem, then the console will register an error on startup, but there should be no issue so long as you follow the tips in the video.

**Comment by phloo75** [comment]
Yeerh i got that :D Great guide! It's working now. 
I would wish that the island was spawned in parts to prevent lag :/ Take that as an idea :D Would be useful! Just like async WE etc.

- And thanks again! Great support!

**Comment by Poslovitch** [comment]
Glad you made that work :)
I'll keep the idea of making spawning the island "chunks" by "chunks". That's right, it's a bit laggy now.
