### ISSUE TITLE
Island Schematics

### ISSUE THREAD

**Issue by Zenya4** [BentoBoxWorld/addon-bskyblock#29]
Allow adding more island schematics than the default 3 islands. This was a feature in ASkyBlock but I do not see such a config option in BSB. Did I miss something out?

**Comment by Poslovitch** [comment]
That's currently not supported in BentoBox, that's planned.

**Comment by rainearojado** [comment]
How do i Change the Default one?

Thanks

**Comment by tastybento** [comment]
@rainearojado Here you go: https://youtu.be/hFkP7hit3i4
