### ISSUE TITLE
Nether island schem doesn't have a nether portal to go back to the overworld

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/addon-bskyblock#3]

**Comment by tastybento** [comment]
This is actually by design. The user can make one if they can make obsidian.

**Comment by Poslovitch** [comment]
I'd prefer to have a nether portal. That is how it works in Minecraft, so players usually don't expect to have to gather the blocks to be able to build a portal in the nether

**Comment by tastybento** [comment]
Okay, one can be added.
