### ISSUE TITLE
Island setting for island members not opening chests still allows them to break them.

### ISSUE THREAD

**Issue by alfie1706** [BentoBoxWorld/addon-bskyblock#5]
Island setting for island members not opening chests still allows them to break them, thus making this entire setting useless unless you want to restrict your members from breaking blocks.

https://youtu.be/0bgaR4ISxuU

**Comment by tastybento** [comment]
Good point. So if opening is not allowed, it should concurrently also protect from breaking.

**Comment by alfie1706** [comment]
My point exactly, there is no point in having a setting to disable opening chests if you can just break it to take contents
