### ISSUE TITLE
End Portal Issue

### ISSUE THREAD

**Issue by BarnabyD** [BentoBoxWorld/addon-bskyblock#6]
Not sure if this is a bentobox api or bskyblock issue.

But when you enter the End Portal from in the nether, it looks like it teleports you to the main island, but standing in the nether portal, which then teleports you back into the nether.

**Comment by tastybento** [comment]
I can't replicate this right now.

With the very first island (at 0,0) the player ends up having their end island overwritten with a default bedrock end island structure, but that's not a portal.

So, question - what config are you using for nether and end worlds?

**Comment by Poslovitch** [comment]
No answers received - closing.
