### ISSUE TITLE
Missing Default Chest Items

### ISSUE THREAD

**Issue by doitliketyler** [BentoBoxWorld/addon-bskyblock#8]
Its seems as though a few items are missing from the default chest and I currently see no way to fix this in the config. Could you please update the start chest to include the following:

- Beetroot Seeds
- Cactus
- Sugar Cane
- Pumpkin Seeds OR Regular Pumpkin

**Comment by tastybento** [comment]
Okay, fixed in the latest commit for BSkyBlock develop branch. Thanks!
